############################################################
# Script 02: Microbial community ecology analysis using microeco
#
# Purpose:
#   This script performs comprehensive microbial community
#   ecological analyses based on ASV tables generated by DADA2.
#   Analyses are conducted using the microeco framework and
#   include:
#
#     - Taxonomic filtering and abundance calculation
#     - Alpha diversity estimation and statistical testing
#     - Differential abundance analysis (LEfSe)
#     - Beta diversity analysis (Bray–Curtis, UniFrac)
#     - Ordination analyses (PCoA, RDA, dbRDA)
#     - Co-occurrence network construction and module detection
#     - Subset analyses by tissue/organ type
#
# Input:
#   - ASV count table (ASV_counts.tsv)
#   - Taxonomic assignment table (ASV_identification.tsv)
#   - Sample metadata (Information.tsv)
#   - Phylogenetic tree (Newick format)
#
# Output:
#   - Alpha diversity tables and figures
#   - Beta diversity ordinations
#   - Differential taxa results (LEfSe)
#   - Network files (GEXF) and node/edge statistics
#
# This script should be executed after:
#   Script 01: DADA2-based ASV inference and preprocessing
#
# Author: [Your Name]
# Affiliation: [Your Institution]
# Date: [YYYY-MM-DD]
############################################################


############################
# 1. Load required packages
############################

# Visualization and phylogenetics
library(ggplot2)
library(ggtree)
library(ggtreeExtra)
library(treeio)
library(tidytree)
library(ape)

# Microbial ecology analysis
library(microeco)
library(GUniFrac)
library(DECIPHER)
library(Biostrings)

# Network analysis
library(igraph)
library(rgexf)
library(WGCNA)

# Data manipulation
library(dplyr)
library(magrittr)
library(stringr)

theme_set(theme_bw())


############################
# 2. Import input data
############################

# Sample metadata
sample_info_16S <- read.csv(
  "~/raw_60/DADA/Information.tsv",
  sep = "\t",
  row.names = 1
)
sample_info_16S$SampleID <- rownames(sample_info_16S)

# ASV count table
otu_table_16S <- read.csv(
  "~/raw_60/DADA/ASV_counts.tsv",
  sep = "\t",
  row.names = 1
)

# Taxonomy table
taxonomy_table_16S <- read.csv(
  "~/raw_60/DADA/ASV_identifiaction.tsv",
  sep = "\t",
  row.names = 1
)

colnames(taxonomy_table_16S) <- c(
  "Kingdom", "Phylum", "Class",
  "Order", "Family", "Genus", "Species"
)

# Add standard taxonomic prefixes
taxonomy_table_16S <- taxonomy_table_16S %>%
  mutate(
    Kingdom = paste0("k_", Kingdom),
    Phylum  = paste0("p_", Phylum),
    Class   = paste0("c_", Class),
    Order   = paste0("o_", Order),
    Family  = paste0("f_", Family),
    Genus   = paste0("g_", Genus),
    Species = paste0("s_", Species)
  )

# Phylogenetic tree
phylo_tree_16S <- read.tree(
  "~/raw_60/DADA/phylogenetic tree/OTUs maximum likelihood tree (HKY80+G4).newick"
)


############################
# 3. Construct microeco dataset
############################

# Harmonize taxonomy structure (required for microeco)
taxonomy_table_16S %<>% tidy_taxonomy

dataset <- microtable$new(
  sample_table = sample_info_16S,
  otu_table    = otu_table_16S,
  tax_table    = taxonomy_table_16S,
  phylo_tree   = phylo_tree_16S
)


############################
# 4. Data filtering and cleaning
############################

# Remove low-abundance and rare taxa
dataset$filter_taxa(rel_abund = 0.0001, freq = 0.1)

# Keep only Bacteria and Archaea
dataset$tax_table %<>%
  subset(Kingdom %in% c("k__Bacteria", "k__Archaea"))

# Remove chloroplast and mitochondrial sequences
dataset$filter_pollution(taxa = c("mitochondria", "chloroplast"))

# Final consistency check
dataset$tidy_dataset()


############################
# 5. Abundance calculation
############################

# Calculate relative abundance tables at all taxonomic levels
dataset$cal_abund()

# Save abundance tables for downstream use
dataset$save_abund(
  dirpath = "~/raw_60/microeco/basic_files/taxa_abund"
)


############################
# 6. Alpha diversity analysis
############################

# Calculate alpha diversity indices
dataset$cal_alphadiv(PD = FALSE)

# Save alpha diversity results
dataset$save_alphadiv(
  dirpath = "~/raw_60/microeco/basic_files/alpha_diversity"
)

# Statistical testing by developmental stage
t_alpha <- trans_alpha$new(dataset = dataset, group = "Stage")

# Overall test
t_alpha$cal_diff(method = "KW")

# Post-hoc Dunn test
t_alpha$cal_diff(method = "KW_dunn")

# Visualization
t_alpha$plot_alpha(measure = "Chao1", y_increase = 0.3)
t_alpha$plot_alpha(measure = "Shannon", y_increase = 0.3)
t_alpha$plot_alpha(measure = "Observed", y_increase = 0.3)
t_alpha$plot_alpha(measure = "InvSimpson", y_increase = 0.3)


############################
# 7. Differential abundance (LEfSe)
############################

t_diff <- trans_diff$new(
  dataset = dataset,
  method  = "lefse",
  group   = "Stage",
  alpha   = 0.01
)

t_diff$plot_diff_bar(threshold = 4)
t_diff$plot_diff_cladogram(
  clade_label_level = 5,
  group_order = c("Bud", "Flower", "R3", "R5")
)


############################
# 8. Beta diversity and ordination
############################

dataset$cal_betadiv(unifrac = TRUE)

t_beta <- trans_beta$new(
  dataset = dataset,
  group   = "Stage",
  measure = "bray"
)

t_beta$cal_ordination(ordination = "PCoA")
t_beta$plot_ordination(
  plot_color = "Stage",
  plot_shape = "Stage",
  plot_type  = c("point", "ellipse")
)


############################
# 9. Co-occurrence network analysis
############################

t_net <- trans_network$new(
  dataset = dataset,
  cor_method = "spearman",
  filter_thres = 0.0001,
  use_WGCNA_pearson_spearman = TRUE
)

t_net$cal_network(COR_p_thres = 0.01, COR_cut = 0.7)
t_net$cal_module(method = "cluster_fast_greedy")

# Save network for external visualization (e.g. Gephi)
t_net$save_network(filepath = "network.gexf")


############################
# 10. Subset analyses by organ
############################

# Separate Pot and Flower samples
group_Pot <- clone(dataset)
group_Pot$sample_table <- subset(group_Pot$sample_table, Organism == "Pot")

group_Flower <- clone(dataset)
group_Flower$sample_table <- subset(group_Flower$sample_table, Organism == "Flower")

# Downstream alpha/beta/network analyses can be repeated per subset
############################################################
# End of Script 02
############################################################
